### PR TITLE
Make `ComposedHookTypes` associative

### PR DESCRIPTION
**Pull request by mcordova47**
As pointed out in my last PR (https://github.com/collegevine/purescript-elmish-hooks/pull/13#discussion_r786936834), `HookType` wasn’t really a monoid, because `ComposedHookTypes` (and therefore `bind`) wasn’t associative. This, I think, fixes that.

### Look, associativity

image

### And it has the expected type

image

### Error message

Here, the second hook is a different type in each of the conditionals. The squiggly line doesn’t show the right place, but I think this was always the case because of `do` notation.

image

### CODE REVIEW

**Review by fsoikin — APPROVED** [review]
Great job!

**Comment by fsoikin** [comment]
Maybe also add a test for this, so it doesn't break later.

**Comment by mcordova47** [comment]
Just realized there is a drawback to this. Now if we have one custom hook that uses another custom hook, we can’t add the first hooks type to the second’s:

```purs
type UseFoo = UseState Int <> UseEffect Unit

useFoo :: Hook UseFoo Unit

-- Doesn’t work
useBar :: Hook (UseFoo <> UseEffect Unit) Unit

-- Works
useBar :: Hook (UseState Int <> UseEffect Unit <> UseEffect Unit) Unit
```

**Comment by fsoikin** [comment]
But you can do this:

```
useBar :: ComposedHookTypes UseFoo (UseEffect Unit) t => Hook t Unit
```

This is a bit inconvenient to use (in Haskell the operator `<>` itself could be a type family), but fortunately you only have to use it if you make new hooks.

**Comment by mcordova47** [comment]
> But you can do this:

Oh nice!


> Maybe also add a test for this, so it doesn't break later.

I was wondering about this. How do I add tests for compile-time guarantees? Should I just add a test that does some grouped `bind`ing? That way if it breaks the test will just fail to compile?

**Comment by fsoikin** [comment]
Yes, that's exactly what I meant for tests.

Technically you could also add a negative test, but that's harder: you can't have it be part of your test code, you have to keep it as a string, and then compile it and check that you get the right error. Do that if you're feeling adventurous, but I really only meant the positive test.

**Pull request merged**
