### PR TITLE
Type safe hooks

### PR DESCRIPTION
**Pull request by mcordova47**
If we redefine `bind`, `discard`, and `pure` using qualified do notation, we can disallow many unsafe conditionals at the type level. I did [basically the same thing as `halogen-hooks`](https://github.com/thomashoneyman/purescript-halogen-hooks/blob/main/src/Halogen/Hooks/Hook.purs) here (except my type annotation for `pure` is different). Here are some examples of type errors:

### Swapping order of hooks

image

### Conditional hook using `when`

image

### Conditional hook using `if … else pure unit`

image

### Limitations

Unfortunately, since `discard hook \_ -> pure unit` adds `Pure` to the `HookType` list, the following doesn’t type check:

image

But it seems like a small inconvenience for the ability to catch unsafe hooks at compile time. Maybe there’s a way to solve this by using a type level list instead of `AppendHookType :: HookType -> HookType -> HookType`. Will have to think more about that, though.

### CODE REVIEW

**Review by fsoikin — APPROVED** [review]
Looks good!

But here's the next thought: now that a hook can only ever be used inside of `withHooks`, _and_ we're guaranteeing the same set and order from render to render, it means that we no longer need unique component names on every individual hook, right?

**Comment by mcordova47** [comment]
> now that a hook can only ever be used inside of `withHooks`, _and_ we're guaranteeing the same set and order from render to render, it means that we no longer need unique component names on every individual hook, right?

Yeah, I was thinking that. We still need it on `withHooks`, though, right?

**Comment by fsoikin** [comment]
Yes we do

**Comment by mcordova47** [comment]
I’ll merge this for now and do that in a future PR

**Pull request merged**
